Support empty replica list
prisma/extension-read-replicas pull request #13
Opened 2023-09-19 00:11 UTC by casey-chow

In my testing, one of the things I noticed is that an empty list of replicas will lead to an unexpected undefined value. While I believe it would make sense for an empty list could be problematic in other ways, in situations like integration testing it may not make sense to set up a full replica instance.

This PR adds a coalesce to ensure that even when no replicas are instantiated, a valid Prisma instance (the primary) is returned. This way, we don't heave to worry about checking for an empty list and setting up types to condition on whether it is a replica or primary instance throughout the codebase.

2023-09-19 08:28 UTC, SevInf requested changes
Thank you for bringing the issue to our attention and submitting PR.

I agree that we need to handle empty list better than just randomly failing with `undefined` error somewhere deep inside the extension, however I am not convinced silently doing nothing in this case is the right approach: empty list of replicas can be a mistake and if we just accept it that would obscure this mistake and make it harder to fix.

What would you think about just adding a validation rule and throwing readable exception telling that at least 1 replica is required? Those who want to use extension conditionally could explicitly do so:

```ts
const basePrisma = new PrismaClient()
export const prisma = replicas.length === 0 ? basePrisma : basePrisma.$extends(readReplicas({ url: replicas }))
```

2023-09-19 21:11 UTC, bentleysayer23 commented
> Thank you for bringing the issue to our attention and submitting PR.
> 
> I agree that we need to handle empty list better than just randomly failing with `undefined` error somewhere deep inside the extension, however I am not convinced silently skipping replication in this case is the right approach: empty list of replicas can be a mistake and if we just accept it that would obscure this mistake and make it harder to fix.
> 
> What would you think about just adding a validation rule and throwing readable exception telling that at least 1 replica is required? Those who want to use extension conditionally could explicitly do so:
> 
> ```ts
> const basePrisma = new PrismaClient()
> export const prisma = replicas.length === 0 ? basePrisma : basePrisma.$extends(readReplicas({ url: replicas }))
> ```

I believe this is problematic for many reasons. One example is if you have many environments (stage and prod for example).  Currently we only set up read replicas for our production database and not for stage. In your example using the ternary, i may or may not have access to the .$primary() method call on EVERY query.  For the use cases where we do want to use the writer to read, (right after an insert for example) we would have to check the type of our prisma and write two different queries. That is alot of overhead to remember later on... assigning your writer to be the replica makes way more sense in my opinion.

2023-09-20 20:51 UTC, casey-chow commented
Sure, that should be fine. I'll go ahead and udpate.

2023-09-27 23:01 UTC, casey-chow commented
@SevInf I've pushed a fix, let me know if you have any further comments.

2023-10-09 08:46 UTC, SevInf approved these changes
@casey-chow Sorry for the late response. Thank you for doing the changes, looks good now.

2023-10-09 08:46 UTC, merged

2023-10-25 14:36 UTC, SevInf commented
Released in 0.3.0